import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomSessionProvider from "./session-provider";
import Navbar from "./navbar/page";
import Analyse from "./analyse/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// {`${geistSans.variable} ${geistMono.variable}؟
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" id="body">
      <body
        className= "antialiased  bg-gray-850 text-gray-900"
      >       
        <CustomSessionProvider>
        <Navbar/>
          {children}
        </CustomSessionProvider>
      </body>
    </html>
  );
}
