import type { Metadata } from "next";
import "./globals.css";
import CustomSessionProvider from "./session-provider";
import Navbar from "./navbar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" id="body">
      <body
        className= "antialiased  bg-gray-850 text-gray-900"
      >       
        <CustomSessionProvider>
        <Navbar/>
          {children}
        </CustomSessionProvider>
      </body>
    </html>
  );
}
